DROP TABLE TB_FUNCIONARIO;

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO(
	ID_FUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(20),
    DATA_NASCIMENTO DATETIME,
    SEXO CHAR(1)
);

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO_DADOS_CONTATO(
	ID_FUNCIONARIO_DADOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_FUNCIONARIO INT NOT NULL,
    TELEFONE_FIXO VARCHAR(15),
	TELEMOVEL VARCHAR(15),
    
    FOREIGN KEY(ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO)
);

